### ISSUE TITLE
Clarifying UI message wording

### ISSUE THREAD

**Issue by zirs3d** [mantso/just.game-issues#10]
System: Ubuntu
Browser: Brave
Wallet: Universal Wallet
(Exchange/app wallet Deposit address method)

Expected Behavior:
User wants to buy xxx boxes

Actual Behavior:

> Send xxx trx to my address below

1. New user has the impression that the tron address can be input, to form the the user's tron address

2. Proceeds to click and select on the text-field with the address pre-populated by Curvy (AI), and gets notifications of text copied to clipboard repeatedly

3. On multiple tries, user eventually realised the concept of a benevolent Curvy (AI-precursor) and her intent.

4. "Xe wanted me to put said TRON into xir address, giveth meth boxeys"

Possible fixes:

3. The wording could be clearer with the following suggestions:
> Send xxx trx to my `personalized` address below

> Send xxx trx to `the` address below

**Comment by mantso** [comment]
Changed the wording. However, the field is not an input box so I think the confusion would not last for very long once the user finds out he/she cannot change the address.

Also, the submit button below the address clarifies the situation even further. ("I've sent it to the address")
