### ISSUE TITLE
Copy icon not copying on some browsers?

### ISSUE THREAD

**Issue by cryptoknighte** [mantso/just.game-issues#12]
- Copy icon (copy ref link or copy wallet) doesn't seem to work for some users
  - Some in brave and I believe some in chrome
  - In that clipboard doesn't contain the text after hitting it

In PROMOTE tab for example, even on Chrome doesn't seem to work

**Comment by mantso** [comment]
Checked all the copy buttons on Brave and Chrome. Cannot reproduce. What OS is this being tested on?

**Comment by cryptoknighte** [comment]
Closing for now unless re-reported
