### ISSUE TITLE
Cannot read property 'txID' of undefined and e.transaction is undefined

### ISSUE THREAD

**Issue by cryptoknighte** [mantso/just.game-issues#13]
- Lots of `Cannot read property 'txID' of undefined` and `e.transaction is undefined`
  - When trying to buy a promotion tag
  - Chrome and Brave PC
  - Even after local storage is reset
  - https://media.discordapp.net/attachments/658544088857182278/658549243623112704/69c11bcb84a6b91f56ea8905cd471c39.png

seems to happen on desktop chrome/brave with tronlink and the universal wallet. Happens of multiple operations. Sometimes when opening boxes, buying boxes, when registering a name or when sending trx to an universal account

For a user that has it, generally they complain about it being persistent after multiple retries and refreshes.

**Comment by JuxxFR** [comment]
Oops, have the same problem today, sorry I open a new issue without check if problem already reported :/

**Comment by cryptoknighte** [comment]
#20 is a duplicate, check there for more details tho

**Comment by cryptoknighte** [comment]
@mantso This continues to be reported several times every day, just FYI

**Comment by cryptoknighte** [comment]
![F919A46A-275B-4F03-927D-DA78003BE594](https://user-images.githubusercontent.com/39616369/71773012-57f3df00-2f0a-11ea-9b54-95a022adc56a.jpeg)

**Comment by mantso** [comment]
The known ways to reproduce this issue have been found & patched. If there's other scenarios and cases in which this occurs, let me know.
