### ISSUE TITLE
Some users unable to login on mobile

### ISSUE THREAD

**Issue by cryptoknighte** [mantso/just.game-issues#16]
- People unable to log in on mobile
  - Login button doesn't respond
  - I believe this is for users on TronLink but unclear, may need to wait for another report

Unfortunately don't have other details

**Comment by JuxxFR** [comment]
In my case, I can login only with Tronlink inDapp.
- It doesn't work with Chrome/Brave (besides the dapp automatically references me with / invite / justfomo)
- I can't select Tronlink after "don't press this button"

Here is my debug errors
![Screenshot (25 déc  2019 21_42_22)](https://user-images.githubusercontent.com/39766629/71450393-4c155980-2761-11ea-8e12-04f944f8ca71.jpg)

**Comment by cryptoknighte** [comment]
Closing unless re-reported
