### ISSUE TITLE
Clearer warning when opening boxes

### ISSUE THREAD

**Issue by cryptoknighte** [mantso/just.game-issues#17]
- Warning when opening boxes
  - Need to warn users when they open boxes
  - With a dialog that makes it clear they are exiting the game
  - Otherwise they think those are divs to collect

**Comment by cryptoknighte** [comment]
This is already improved and could be closed. If we wanted to improve further:

- consider adding a note they will be exiting the game if they open 
- consider showing the amount of trx they will get as they exit and specify that’s total amount if they walk away

Even if not, this is already a lot better with current warning 👍 

From another user: 

> In the top left corner, by the box icon, maybe clarify for non thinkers - that the value/number there is not the value per box but is the total sum of tron for all your owned boxes? I think we get less bad rep and less stoopid box opens. When they think it’s the value per box, they sell based on the wrong reasons. It’s not UI’s fault if that is clear and they open boxes anyway though.

**Comment by mantso** [comment]
Fixed.
