### ISSUE TITLE
Selecting to Spend 100% of Tron

### ISSUE THREAD

**Issue by ghost** [mantso/just.game-issues#2]
## Expected Behavior

Expect when selecting to spend 100% of Tron that the transaction goes through.

## Actual Behavior
Transaction does not go through and reverts.

## Steps to Reproduce the Problem
- Select 100% of Tron with slider or button.
- Send transaction.

## Specifications
Chromium
TronLink

**Comment by letugade** [comment]
You need a bit of Tron in your account to cover the transaction fee.

**Comment by 0x10F** [comment]
Yes, however, if you're selecting to purchase all the boxes you can with your Tron as suggested by the UI shouldn't this be compensated for?

**Comment by mantso** [comment]
This is fixed now.
