### ISSUE TITLE
Stuck on "Authenticating..." screen

### ISSUE THREAD

**Issue by fl4ke** [mantso/just.game-issues#21]
# Expected Behavior
Successfully login user to just.game

# Actual Behavior
Stuck on "Authenticating..." screen.

# Steps to Reproduce the Problem

1. Log off TronLink
2. Visit just.game (TronLink option is grey and unclickable for now as it should)
3. Log into TronLink Account
4. Click on the login with TronLink option (it just got clickable)
You should now be stuck on the "Authenticating..." screen.

Specifications
Login Method: TronLink

**Comment by JuxxFR** [comment]
I had this issue and had to hard refresh on deskop

**Comment by mantso** [comment]
We were suffering from some DDoS shenanigans. It should be resolved now.
