### ISSUE TITLE
Ability to transition from universal wallet to TronLink

### ISSUE THREAD

**Issue by cryptoknighte** [mantso/just.game-issues#27]
Several users asked about how to transition from the in game universal wallet to TronLink. In particular, how to import the wallet into their TronLink 

I don’t believe this is possible now. What would you recommend we tell these users when they ask 

Concern: How to access their wallet if the site goes down, is there a backup?

**Comment by mantso** [comment]
It may be on our roadmap soon. There's no backup currently, it was planned, but we're reevaluating the direction we need to take for the game.
