### ISSUE TITLE
TRX amounts on the checkout sidebar can be confusing

### ISSUE THREAD

**Issue by cryptoknighte** [mantso/just.game-issues#28]
Reported by Incognito:

Meco sent this over - it looks like the withdraw/convert functions for refs aren't doing what they're supposed to be doing. Can someone else have a look at this just to check I'm not misunderstanding ?https://cdn.discordapp.com/attachments/475639389263888415/660447897438912513/JustGame.mp4

-----

Don't know if it was already discussed.. Just pressed "convert" under promote..There I can just see my small amount of Refs.. but the txn that is initiated is my whole amount of TRX .. Royalties included.. this is fcking dangerous.. if you do not check it twice. I know you always should... And of course I did.. but.. wow <:monkaW:475277153941061634>

![](https://cdn.discordapp.com/attachments/658544088857182278/660433095438106644/unknown.png)

now I see.. both buttons are not even taking the ref earnings into consideration.. both are focusing on the royalties.. so as I am seeing it right now, it wants to open my boxes when pressing withdraw to get my refs.

**Comment by mantso** [comment]
This is fixed now.
