### ISSUE TITLE
Why does this user show up in top 100 persistently?

### ISSUE THREAD

**Issue by cryptoknighte** [mantso/just.game-issues#29]
User iannoni79:

> hello, can you explain to me why without investing i always stay in the ranking of 100 ....?
> pos 49 ATRX 1.186.701 4
> autoplay isn’t on
> haven’t reinvested 
> no, I'm not doing anything
> I bought yesterday and then I didn't do anything. now I have moved to position 49
> first I arrived in position 100 and without doing anything I started from position 1

Seemed confused why they still show up in top 100

**Comment by mantso** [comment]
Revive mechanic.
