### ISSUE TITLE
Virtual Payroll not showing all transactions, Glitch UI reports false positives.

### ISSUE THREAD

**Issue by sdirsodk34** [mantso/just.game-issues#33]
Virtual Payroll either lags behind, or doesn't display a portion of the transactions. Not sure what additional info there is, but it happens frequently. 

Also, the Glitch timer falsely reports "The Glitch has gone off and it will be validated on the next block" when the timer is low and a buy resets it. For example it was at 7 min earlier, someone bought 70K Trx worth of boxes, and it reported the above for a couple of seconds before it reset to 59:59.
(The 70K TRX buy also slipped through virtual payroll)

**Comment by mantso** [comment]
False positives should be fixed now.
