### ISSUE TITLE
UI when Glitch goes off is too confusing, needs to be better explained on the site.

### ISSUE THREAD

**Issue by sdirsodk34** [mantso/just.game-issues#34]
Lots of people including myself were confused when the first glitch went off.

The centre of the confusion is that the payout goes into the 2x or "OPEN NOW TO GET" section.
So, if the glitch is 30mil trx, and I have a total of 1% stake in the box distribution, I'd expect 300k trx to be show on the top left of the site where it says "COLLECTED ROYALTIES", not on my 2x section.

Solution to this could be a separate box titled "GLITCH WINNINGS" , or an explanatory text that explains that the glitch amount has the 2x factored in.

I understand that this is due to the naming of things, eg. 1x and 2x, but it still needs to be clearer.

**Comment by mantso** [comment]
The Glitch page contains the amount a user would receive if the boxes were opened before the end of the round. I understand this caused confusion. The number on the Glitch page will now reflect the baseline 1x value.
