### ISSUE TITLE
Reinvest using both your collected royalties and promo earnings needs to be made crystal clear to the players.

### ISSUE THREAD

**Issue by sdirsodk34** [mantso/just.game-issues#35]
Not sure if those two can be made separate post launch as that would be the best solution.

If not, the fact that reinvesting your boxes *or* your promo earnings, reinvests the other one too should be as clear as possible, and certainly in the same tab.

Also, the reinvest button displaying the number of new boxes you'll get after reinvesting doesn't account for promo earnings at all, which can be very confusing as it might say you'll get X new boxes, a number that aligns with your collected royalties, but after you've clicked it'd use your promo earnings too. 

Needs a fix urgently.

**Comment by mantso** [comment]
Removed the button to reinvest from the promotion page for now.
