### ISSUE TITLE
Wallet Issue

### ISSUE THREAD

**Issue by cryptonomad11** [mantso/just.game-issues#4]
System: Windows 10
Browser: Brave
Wallet: Tronlink
After hard-refreshing the website, the wallet showed 0 balance and had connectivity issues with the UI not recognizing any wallet connected. I tried to hard refresh again and connect to the node once again but the issue remains.
I hope this helps so far I will be looking for more.
PS: Thank you for your awesome work so far <3 it looks really amazing I am speechless tbh ^^

**Comment by mantso** [comment]
Let me know if this issue persists in Testnet 3

**Comment by cryptonomad11** [comment]
I haven't witnessed any issues with the wallet on the testnet 3. But all the compliments to you and Justo, just amazing job, I really love the concept and the detail, it's so much more then what I expected <3

**Comment by cryptoknighte** [comment]
Closing for now I don't believe this is still an issue
