### ISSUE TITLE
LAST 100 Leaderboard Sort issue

### ISSUE THREAD

**Issue by wonnim** [mantso/just.game-issues#5]
**Expected Behavior**
The Last 100 leaderboard should show the last 100 participants.

**Actual Behavior**
It shows participants but it has a bunch of empty spots in between participants. See image below.
In the below image minnow should be in the 82nd position on the leaderboard.
Image: [here](https://imgur.com/M15JVVr)

**Steps to Reproduce the Problem**
Go to the site https://beta.just.game/start

**Specifications**
Operating System: Windows
Browser: Chrome

**Comment by mantso** [comment]
A temporary fixed for this is refreshing the page, or when another transaction comes in it's also refreshed. Reason for this bug is known, permanent fix incoming soon(c)(tm).
