### ISSUE TITLE
can only connect in private mode

### ISSUE THREAD

**Issue by likwit** [mantso/just.game-issues#7]
Expected Behavior
login with tronlink

Actual Behavior
when i try to login with tronlink it says tronlink not connected.

Steps to Reproduce the Problem
1. login with universal wallet
2. clear browsing data
3. try to login with your tronlink wallet
4. go to private mode and login with tronlink wallet

Specifications
Operating System: windows 10
browser: google chrome
tron link address. TKPqkPBp5vNgwBMXNGeHX5fFCpAZxgBHin
Login Method: tron link

**Comment by mantso** [comment]
Please visit `https://just.game/logout` to clear out the cookie that automatically logs you in. If you are using the universal wallet, make sure you have the credentials of the registration email at hand. It's the only way you can log in again.
