### ISSUE TITLE
UI displays a different price for the same amount of boxes between Customized Examples and buying manually. 

### ISSUE THREAD

**Issue by sdirsodk34** [mantso/just.game-issues#9]
**Expected Behavior**
User wants to buy 949 boxes
**Actual Behavior**
Customized Examples shows 949 boxes costing 23744 TRX, while choosing manually shows 23725.

**Image**
https://cdn.discordapp.com/attachments/657437962837032971/657989424948183060/unknown.png

**Comment by mantso** [comment]
Rounding error, no priority for now.
